name:                postgresql-tx-simple
version:             0.2.0.1
github:              "simspace/postgresql-tx"
license:             BSD3
license-file:        LICENSE.md
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            postgresql-tx interfacing for use with postgresql-simple.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.10.0 && < 0.11
- postgresql-simple >= 0.6.2 && < 0.7
- postgresql-tx >= 0.2.0.0 && < 0.3
- transformers >= 0.5.6.2 && < 0.6

library:
  source-dirs: src
