name:                postgresql-tx
version:             0.2.0.0
github:              "simspace/postgresql-tx"
license:             BSD3
license-file:        LICENSE.md
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            A safe transaction monad for use with various PostgreSQL Haskell libraries.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6.2 && < 0.6

library:
  source-dirs: src
