resolver: lts-16.8

packages:
- .
- example
- monad-logger
- persistent
- query
- simple
- squeal
- squeal/compat/simple

extra-deps:
# {{{ postgresql-query
- git: https://github.com/Simspace/postgresql-query
  commit: b45346d7af5a5de6f083349ac1fcee830afe4112
# }}}

# {{{ squeal
- squeal-postgresql-0.7.0.1
- free-categories-0.2.0.2
# }}}
