resolver: lts-16.8

packages:
- .
- example
- monad-logger
- persistent
- query
- simple
- squeal
- squeal/compat/simple

extra-deps:
- postgresql-simple-0.6.3
- postgresql-query-3.8.1

# {{{ squeal
- squeal-postgresql-0.8.1.1
- free-categories-0.2.0.2
# }}}
