name:                postgresql-tx-monad-logger
version:             0.2.0.0
github:              "simspace/postgresql-tx/monad-logger"
license:             BSD3
license-file:        LICENSE.md
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            postgresql-tx interfacing for use with monad-logger.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- monad-logger >= 0.3.32 && < 0.4
- postgresql-tx >= 0.2.0.0 && < 0.3

library:
  source-dirs: src
