name:                postgresql-tx-query
version:             0.2.0.0
github:              "simspace/postgresql-tx/query"
license:             BSD3
license-file:        LICENSE.md
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            postgresql-tx interfacing for use with postgresql-query.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- exceptions >= 0.10.4 && < 0.11
- monad-control >= 1.0.2.3 && < 1.1
- monad-logger >= 0.3.32 && < 0.4
- mtl >= 2.2.2 && < 2.3
- postgresql-query >= 3.5.0 && < 3.6
- postgresql-simple >= 0.6.2 && < 0.7
- postgresql-tx >= 0.2.0.0 && < 0.3
- postgresql-tx-monad-logger >= 0.2.0.0 && < 0.3
- transformers >= 0.5.6.2 && < 0.6
- transformers-base >= 0.4.5.2 && < 0.5

library:
  source-dirs: src
